version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MYSQL_DB=${MYSQL_DB}
    ports:
      - "3000:3000"
    environment:
      - MYSQL_DB=${MYSQL_DB}
      # The port for the database MCP server, used internally by the API proxy
      - MCP_DB_SERVERPORT=8001
      # The base URL for the backend, as seen from the container itself
      - BACKEND_BASE_URL=http://localhost:8000
    volumes:
      - .:/app
      - /app/node_modules 