@startuml
title Create Briefing

actor User
participant "LI" as LI
participant "FE" as FE
participant "BE" as BE
participant "DB" as DB

User -> LI: opens linkedin
LI -> FE: 👁️ notices
FE -> BE: GET /draft_messages/
BE -> DB: retrieve messages of type "DRAFT"
DB --> BE: messages
BE --> FE: messages
FE --> LI: display messages
@enduml
