@startuml
actor LI
participant FE
participant BE
participant DB as "DB(SQL)"
participant AGENT
participant MCP

LI <- FE: user rejects draft
FE -> BE: POST /reject-draft/ (user id,draft message id)
BE -> DB: get agent_id from draft message (by message_id)
BE -> DB: remove draft from DB (by message_id)
BE -> DB: remove agent from agents table (by agent_id)
BE --> FE: 200 OK
@enduml
